### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by slcheng97** [naver-ai/egtr#1]
Dear Authors,

I have a keen interest in your recent work and find it very insightful. I am eagerly anticipating the release of your code. Could you please inform me if it will be made available within the next two weeks?

I truly appreciate your efforts and look forward to your response.

Thank you very much.

**Comment by jinbae** [comment]
Thank you for your interest in our work.
While it's difficult to provide a definite answer on whether we can release the code within two weeks, we'll strive to make it available as soon as possible.
(We are currently very busy with other tasks, and it's not easy to estimate how long the internal review process within the company will take.)

I apologize for not providing a clear response.
Thank you very much.

**Comment by jinbae** [comment]
Code has just been released.
I am very sorry for not releasing it until more than two months later.
Thank you so much for waiting patiently.
I'll close the issue.
