### ISSUE TITLE
ARTIFACT PATH

### ISSUE THREAD

**Issue by Mikael17125** [naver-ai/egtr#4]
`python evaluate_egtr.py --data_path dataset/visual_genome --artifact_path $ARTIFACT_PATH`
Can you explain what is $ARTIFACT_PATH or can you give me sample command to run the evaluation code?

Thank you.

**Comment by niloofarAzari** [comment]
Hi, I have the same question, how did you solve it?

**Comment by niloofarAzari** [comment]
> `python evaluate_egtr.py --data_path dataset/visual_genome --artifact_path $ARTIFACT_PATH` Can you explain what is $ARTIFACT_PATH or can you give me sample command to run the evaluation code?
> 
> Thank you.

Hi, I have the same question, how did you solve it?

**Comment by jzzzzh** [comment]
the direction of the pretrained model .ckpt
