### ISSUE TITLE
about pretrained

### ISSUE THREAD

**Issue by xfufu0724** [naver-ai/egtr#6]
Hello，I encountered some issues when loading the checkpoint. When I want to train the EGTR model,Which .ckpt file should be specifically used for the 'pretrained' in the command line: python train_egtr.py --data_path dataset/visual_genome --output_path $OUTPUT_PATH --pretrained $PRETRAINED_PATH --memo $MEMO ?

Looking forward to your response. Thank you.

**Comment by xfufu0724** [comment]
@jinbae

**Comment by jinbae** [comment]
We used pre-trained object detector to train EGTR, and our pre-trained object detector are publicly available.
Please refer to the readme.

![image](https://github.com/user-attachments/assets/9798f997-c55d-47c0-8d67-d00378892bfc)

Download the pre-trained object detector and set the downloaded path as PRETRAINED_PATH.

**Comment by xfufu0724** [comment]
I have downloaded pre-trained object detector and extracted it to the path of the code.
![微信图片_20240723172802](https://github.com/user-attachments/assets/e976d829-aafb-4cce-833e-562082109f4a)

The parameter **pretrained** seems to require loading a JSON files,  i tried to load "epoch=03-validation_loss=1.71__test__26446__V100-PCIE-32GB.json" file. But when I load the JSON file, the following error occurs：
_OSError: Unable to load weights from pytorch checkpoint file for './pretrained_detr__SenseTime__deformable-detr/batch__32__epochs__150_50__lr__1e-05_0.0001__visual_genome__finetune/version_0/config.json' at './pretrained_detr__SenseTime__deformable-detr/batch__32__epochs__150_50__lr__1e-05_0.0001__visual_genome__finetune/version_0/config.json'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True._

**Comment by hanchuqi** [comment]
@xfufu0724  I'm having the same issue, how did you fix it?

**Comment by xfufu0724** [comment]
> @xfufu0724 我遇到了同样的问题，您是如何解决的？

具体我不太记得了，你看看能不能找到设置from_tf的代码，似乎改成from_tf=True就行了？
