### ISSUE TITLE
Trained EGTR model

### ISSUE THREAD

**Issue by thomasfoltz** [naver-ai/egtr#8]
@jinbae I appreciate the documentation for this work! However, I currently don't have enough compute to train my own custom EGTR model on the Visual Genome Dataset. Would you make those weights publicly available? Thank you!

For others to reference, this is the memory error I run into when there isn't sufficient GPU memory to train. I had to set the `--gpus` arg to 1 since I don't have 8 GPUS available.

![image](https://github.com/user-attachments/assets/900797d8-82d3-4c61-b427-c71d3a38a32d)

**Comment by jinbae** [comment]
Our model weights were already made public. Please refer to the readme.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/762d8683-dd10-4a33-baed-5fe79eeb38d5">

**Comment by trongminh03** [comment]
The error is due to insufficient shared memory. If you're using Docker, try allocating more shared memory by using the "--shm-size" option when running the Docker image. Hope this helps!

**Comment by thomasfoltz** [comment]
Thanks for the advice! It turns out it wasn't an issue with the weights I was using, but rather the insufficient shared memory as @trongminh03 mentioned. Now it is running, but unfortunately, since I am only using one RTX 4070, I can only train with a batch size of 1.
